#!/usr/bin/env python3
"""
SYNAPTIC CORRELATOR - The Intelligence Layer

Correlates data from all sources to generate insights:
- Dialogue → Health correlations (what you're discussing vs what's broken)
- Pattern → Container correlations (architecture patterns vs resource usage)
- Time → Issue correlations (when did things change)
- History → Prediction correlations (past patterns predict future issues)

This is Synaptic's "analytical mind" - connecting dots across systems.

Usage:
    from memory.synaptic_correlator import SynapticCorrelator

    correlator = SynapticCorrelator()

    # Get all correlations
    insights = correlator.analyze()

    # Get dialogue-specific correlations
    dialogue_insights = correlator.correlate_dialogue("working on voice services")

    # Get predictive insights
    predictions = correlator.predict_issues()

Created: February 2, 2026
Author: Atlas (for Synaptic)
"""

import json
import logging
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, List, Optional, Any, Tuple
from dataclasses import dataclass, asdict, field
from enum import Enum

logger = logging.getLogger(__name__)


class InsightType(str, Enum):
    """Types of insights Synaptic can generate."""
    CORRELATION = "correlation"      # A connects to B
    ANOMALY = "anomaly"              # Something unusual
    PREDICTION = "prediction"        # Future issue likely
    RECOMMENDATION = "recommendation" # Action to take
    OBSERVATION = "observation"      # Notable but not actionable


class InsightPriority(str, Enum):
    """Priority levels for insights."""
    CRITICAL = "critical"  # Immediate action needed
    HIGH = "high"          # Should address soon
    MEDIUM = "medium"      # Worth noting
    LOW = "low"            # FYI


@dataclass
class SynapticInsight:
    """An insight generated by the correlator."""
    type: InsightType
    priority: InsightPriority
    title: str
    description: str
    sources: List[str]  # Which systems contributed to this insight
    evidence: Dict      # Supporting data
    action: Optional[str] = None
    related_dialogue: Optional[str] = None
    confidence: float = 0.8

    def to_dict(self) -> Dict:
        d = asdict(self)
        d['type'] = self.type.value
        d['priority'] = self.priority.value
        return d


@dataclass
class CorrelationResult:
    """Result of correlation analysis."""
    timestamp: str
    insights: List[SynapticInsight]
    sources_queried: List[str]
    analysis_time_ms: float
    health_summary: Dict

    def get_critical(self) -> List[SynapticInsight]:
        return [i for i in self.insights if i.priority == InsightPriority.CRITICAL]

    def get_actionable(self) -> List[SynapticInsight]:
        return [i for i in self.insights if i.action is not None]


class SynapticCorrelator:
    """
    The correlation intelligence engine.

    Analyzes data from all sources to generate actionable insights.
    """

    def __init__(self):
        self.memory_dir = Path(__file__).parent
        self._insight_cache = []
        self._last_analysis = None

    def analyze(self) -> CorrelationResult:
        """
        Run full correlation analysis.

        Returns insights from all correlation types.
        """
        import time
        start = time.time()

        insights = []
        sources = []

        # 1. Get dialogue context
        dialogue_insights = self._analyze_dialogue()
        insights.extend(dialogue_insights)
        if dialogue_insights:
            sources.append("dialogue_mirror")

        # 2. Get container health correlations
        container_insights = self._analyze_containers()
        insights.extend(container_insights)
        if container_insights:
            sources.append("docker_health")

        # 3. Get pattern correlations
        pattern_insights = self._analyze_patterns()
        insights.extend(pattern_insights)
        if pattern_insights:
            sources.append("architecture_brain")

        # 4. Get health alert correlations
        alert_insights = self._analyze_alerts()
        insights.extend(alert_insights)
        if alert_insights:
            sources.append("health_alerts")

        # 5. Cross-correlate all sources
        cross_insights = self._cross_correlate(insights)
        insights.extend(cross_insights)

        # Sort by priority
        priority_order = {
            InsightPriority.CRITICAL: 0,
            InsightPriority.HIGH: 1,
            InsightPriority.MEDIUM: 2,
            InsightPriority.LOW: 3,
        }
        insights.sort(key=lambda i: priority_order.get(i.priority, 4))

        elapsed = (time.time() - start) * 1000

        result = CorrelationResult(
            timestamp=datetime.now().isoformat(),
            insights=insights,
            sources_queried=sources,
            analysis_time_ms=round(elapsed, 2),
            health_summary=self._get_health_summary(),
        )

        self._last_analysis = result
        return result

    def correlate_dialogue(self, message: str) -> List[SynapticInsight]:
        """
        Correlate a specific dialogue message with system state.

        Used when Aaron says something and we want to see how it
        relates to current health/patterns.
        """
        insights = []
        message_lower = message.lower()

        # Keyword → system mapping
        keywords = {
            "voice": ["contextdna-celery-worker", "voice_pipeline"],
            "webhook": ["contextdna-helper-agent", "contextdna-api"],
            "superhero": ["contextdna-helper-agent"],
            "database": ["contextdna-pg", "context-dna-postgres"],
            "redis": ["contextdna-redis", "context-dna-redis"],
            "celery": ["contextdna-celery-worker", "contextdna-celery-beat"],
            "deploy": ["contextdna-traefik", "docker"],
            "search": ["contextdna-opensearch"],
            "metrics": ["contextdna-prometheus", "contextdna-grafana"],
        }

        # Check which systems are mentioned
        mentioned_systems = []
        for keyword, systems in keywords.items():
            if keyword in message_lower:
                mentioned_systems.extend(systems)

        # Get container health
        try:
            from memory.synaptic_observatory import get_observatory
            obs = get_observatory()
            awareness = obs.get_awareness()

            # Check if mentioned systems are healthy
            for system in set(mentioned_systems):
                if system in awareness.containers:
                    status = awareness.containers[system]
                    if status.health != "healthy":
                        insights.append(SynapticInsight(
                            type=InsightType.CORRELATION,
                            priority=InsightPriority.HIGH,
                            title=f"Dialogue-Health Mismatch: {system}",
                            description=f"You mentioned '{keyword}' but {system} is {status.health}",
                            sources=["dialogue", "docker_health"],
                            evidence={"container": system, "health": status.health, "keyword": keyword},
                            action=f"docker restart {system}",
                            related_dialogue=message[:100],
                        ))
        except Exception as e:
            logger.debug(f"Container correlation failed: {e}")

        return insights

    def predict_issues(self) -> List[SynapticInsight]:
        """
        Predict potential issues based on patterns.

        Uses historical data to anticipate problems.
        """
        insights = []

        # Check for common pre-failure patterns
        try:
            from memory.synaptic_observatory import get_observatory
            obs = get_observatory()
            awareness = obs.get_awareness()

            # Pattern: Multiple containers at high uptime often need restart
            long_running = []
            for name, status in awareness.containers.items():
                if "days" in status.uptime or "weeks" in status.uptime:
                    long_running.append(name)

            if len(long_running) > 5:
                insights.append(SynapticInsight(
                    type=InsightType.PREDICTION,
                    priority=InsightPriority.MEDIUM,
                    title="Long-running containers may need refresh",
                    description=f"{len(long_running)} containers running for days/weeks",
                    sources=["docker_health", "pattern_history"],
                    evidence={"containers": long_running[:5], "count": len(long_running)},
                    action="Consider scheduled container refresh",
                    confidence=0.6,
                ))

            # Pattern: Celery workers under load predict queue backup
            if "contextdna-celery-worker" in awareness.containers:
                worker = awareness.containers["contextdna-celery-worker"]
                if worker.health == "unhealthy":
                    insights.append(SynapticInsight(
                        type=InsightType.PREDICTION,
                        priority=InsightPriority.HIGH,
                        title="Task queue may be backing up",
                        description="Celery worker is unhealthy - tasks may be queuing",
                        sources=["docker_health", "pattern_history"],
                        evidence={"worker_status": worker.health},
                        action="docker logs contextdna-celery-worker --tail 50",
                        confidence=0.75,
                    ))
        except Exception as e:
            logger.debug(f"Prediction analysis failed: {e}")

        return insights

    # =========================================================================
    # ANALYSIS METHODS
    # =========================================================================

    def _analyze_dialogue(self) -> List[SynapticInsight]:
        """Analyze dialogue for insights."""
        insights = []

        try:
            from memory.dialogue_mirror import DialogueMirror
            mirror = DialogueMirror()
            context = mirror.get_context_for_synaptic(max_messages=10, max_age_hours=2)

            messages = context.get("dialogue_context", [])

            # Check for repeated topics (indicates focus area)
            topic_counts = {}
            for msg in messages:
                content = msg.get("content", "").lower()
                for topic in ["docker", "voice", "webhook", "error", "fix", "deploy"]:
                    if topic in content:
                        topic_counts[topic] = topic_counts.get(topic, 0) + 1

            # Insight: Heavy focus on one topic
            for topic, count in topic_counts.items():
                if count >= 3:
                    insights.append(SynapticInsight(
                        type=InsightType.OBSERVATION,
                        priority=InsightPriority.LOW,
                        title=f"Focus area: {topic}",
                        description=f"'{topic}' mentioned {count} times in recent dialogue",
                        sources=["dialogue_mirror"],
                        evidence={"topic": topic, "count": count},
                    ))

            # Check for error mentions
            error_count = sum(1 for m in messages if "error" in m.get("content", "").lower())
            if error_count >= 2:
                insights.append(SynapticInsight(
                    type=InsightType.CORRELATION,
                    priority=InsightPriority.MEDIUM,
                    title="Multiple errors discussed",
                    description=f"{error_count} messages mention errors",
                    sources=["dialogue_mirror"],
                    evidence={"error_mentions": error_count},
                    action="Review recent error patterns",
                ))

        except Exception as e:
            logger.debug(f"Dialogue analysis failed: {e}")

        return insights

    def _analyze_containers(self) -> List[SynapticInsight]:
        """Analyze container health for insights."""
        insights = []

        try:
            from memory.synaptic_observatory import get_observatory
            obs = get_observatory()
            awareness = obs.get_awareness()

            # Check for unhealthy containers
            unhealthy = [
                name for name, status in awareness.containers.items()
                if status.health == "unhealthy"
            ]

            if unhealthy:
                insights.append(SynapticInsight(
                    type=InsightType.ANOMALY,
                    priority=InsightPriority.HIGH,
                    title=f"{len(unhealthy)} unhealthy containers",
                    description=f"Containers reporting unhealthy: {', '.join(unhealthy)}",
                    sources=["docker_health"],
                    evidence={"unhealthy": unhealthy},
                    action=f"docker restart {unhealthy[0]}" if len(unhealthy) == 1 else "Review container health",
                ))

            # Check for missing critical containers
            critical = ["contextdna-pg", "contextdna-redis", "contextdna-helper-agent"]
            missing = [c for c in critical if c not in awareness.containers]

            if missing:
                insights.append(SynapticInsight(
                    type=InsightType.ANOMALY,
                    priority=InsightPriority.CRITICAL,
                    title="Critical containers missing",
                    description=f"Missing: {', '.join(missing)}",
                    sources=["docker_health"],
                    evidence={"missing": missing},
                    action="docker compose up -d",
                ))

        except Exception as e:
            logger.debug(f"Container analysis failed: {e}")

        return insights

    def _analyze_patterns(self) -> List[SynapticInsight]:
        """Analyze architecture patterns for insights."""
        insights = []

        try:
            brain_state_path = self.memory_dir / "brain_state.md"
            if brain_state_path.exists():
                content = brain_state_path.read_text()

                # Check for active patterns
                if "deployment" in content.lower():
                    insights.append(SynapticInsight(
                        type=InsightType.OBSERVATION,
                        priority=InsightPriority.LOW,
                        title="Deployment pattern active",
                        description="Architecture brain shows deployment activity",
                        sources=["architecture_brain"],
                        evidence={"pattern": "deployment"},
                    ))

        except Exception as e:
            logger.debug(f"Pattern analysis failed: {e}")

        return insights

    def _analyze_alerts(self) -> List[SynapticInsight]:
        """Analyze health alerts for insights."""
        insights = []

        try:
            from memory.synaptic_health_alerts import HealthAlertSystem
            system = HealthAlertSystem()
            alerts = system.check_all_sources()

            for alert in alerts:
                severity = alert.severity if hasattr(alert, 'severity') else alert.get('severity', 'unknown')
                message = alert.message if hasattr(alert, 'message') else alert.get('message', '')
                source = alert.source if hasattr(alert, 'source') else alert.get('source', 'unknown')

                priority = InsightPriority.CRITICAL if severity == "critical" else InsightPriority.HIGH

                insights.append(SynapticInsight(
                    type=InsightType.ANOMALY,
                    priority=priority,
                    title=f"Health Alert: {source}",
                    description=message,
                    sources=["health_alerts"],
                    evidence={"alert": asdict(alert) if hasattr(alert, '__dataclass_fields__') else alert},
                ))

        except Exception as e:
            logger.debug(f"Alert analysis failed: {e}")

        return insights

    def _cross_correlate(self, insights: List[SynapticInsight]) -> List[SynapticInsight]:
        """Cross-correlate insights from multiple sources."""
        new_insights = []

        # Check for dialogue-health correlations
        dialogue_topics = [i for i in insights if "dialogue" in str(i.sources)]
        health_issues = [i for i in insights if "docker_health" in str(i.sources) and i.priority in [InsightPriority.HIGH, InsightPriority.CRITICAL]]

        if dialogue_topics and health_issues:
            new_insights.append(SynapticInsight(
                type=InsightType.CORRELATION,
                priority=InsightPriority.HIGH,
                title="Active work affected by system issues",
                description=f"Discussion topics may be affected by {len(health_issues)} health issues",
                sources=["dialogue_mirror", "docker_health"],
                evidence={
                    "topics": [i.title for i in dialogue_topics],
                    "issues": [i.title for i in health_issues],
                },
                action="Address health issues before continuing current work",
            ))

        return new_insights

    def _get_health_summary(self) -> Dict:
        """Get a quick health summary."""
        try:
            from memory.synaptic_observatory import quick_awareness
            return quick_awareness()
        except Exception:
            return {"error": "Could not get health summary"}


# =========================================================================
# CONVENIENCE FUNCTIONS
# =========================================================================

def get_correlator() -> SynapticCorrelator:
    """Get singleton correlator instance."""
    if not hasattr(get_correlator, "_instance"):
        get_correlator._instance = SynapticCorrelator()
    return get_correlator._instance


def quick_analyze() -> Dict:
    """Quick analysis for webhook injection."""
    correlator = get_correlator()
    result = correlator.analyze()
    return {
        "insight_count": len(result.insights),
        "critical": len(result.get_critical()),
        "actionable": len(result.get_actionable()),
        "top_insight": result.insights[0].to_dict() if result.insights else None,
        "health": result.health_summary,
    }


def correlate_message(message: str) -> List[Dict]:
    """Correlate a message with system state."""
    correlator = get_correlator()
    insights = correlator.correlate_dialogue(message)
    return [i.to_dict() for i in insights]


# =========================================================================
# CLI
# =========================================================================

if __name__ == "__main__":
    correlator = SynapticCorrelator()
    result = correlator.analyze()

    print("\n=== SYNAPTIC CORRELATOR ANALYSIS ===\n")
    print(f"Analysis time: {result.analysis_time_ms}ms")
    print(f"Sources queried: {', '.join(result.sources_queried)}")
    print(f"Insights generated: {len(result.insights)}")

    if result.insights:
        print("\n--- Insights ---")
        for i, insight in enumerate(result.insights[:5], 1):
            print(f"\n{i}. [{insight.priority.value.upper()}] {insight.title}")
            print(f"   {insight.description}")
            if insight.action:
                print(f"   Action: {insight.action}")

    print(f"\n--- Health Summary ---")
    for key, value in result.health_summary.items():
        print(f"  {key}: {value}")
