#!/usr/bin/env python3
"""
Synaptic Chat Route - Direct Voice Relay (No LLM Re-Reasoning)

This module provides Chat UI responses by DIRECTLY relaying Synaptic's
memory data, without passing it through an LLM that would re-reason
and potentially hallucinate.

ARCHITECTURE:
- Uses get_8th_intelligence_data() from synaptic_voice.py (PROTECTED)
- Formats output conversationally
- NO LLM involvement - pure data relay with structure preserved

PROBLEM THIS SOLVES:
- LLM was re-reasoning Synaptic's data and hallucinating (e.g., "aiohttp" vs "asyncio.to_thread()")
- Structure/patterns from memory were being discarded
- This module preserves accuracy by direct relay

SAFE TO MODIFY: This file only affects Chat UI
PROTECTED: synaptic_voice.py, persistent_hook_structure.py

REVERSIBILITY:
- To revert: Set USE_DIRECT_ROUTE = False in synaptic_chat_server.py
- Or delete this file entirely
- Webhook path is NEVER touched
"""

from typing import Dict, Any, Tuple, List


def get_chat_response(user_msg: str) -> str:
    """
    Chat UI response - isolated from webhook path.

    Direct relay of Synaptic's memory data, formatted conversationally.
    NO LLM re-reasoning - preserves accuracy of stored learnings.

    Args:
        user_msg: Aaron's message to Synaptic

    Returns:
        Formatted response string with memory data
    """
    from memory.synaptic_voice import get_8th_intelligence_data

    data = get_8th_intelligence_data(user_msg)

    if not data:
        return _quiet_response()

    return _format_response(data, user_msg)


def _quiet_response() -> str:
    """Response when Synaptic's signal is quiet."""
    return (
        "My signal is quiet right now, Aaron.\n\n"
        "I don't have relevant patterns or learnings surfacing for this topic. "
        "After we work through it together, I'll remember for next time."
    )


def _format_response(data: Dict[str, Any], user_msg: str) -> str:
    """
    Format Synaptic's data conversationally - direct relay, not re-reasoning.

    Structure:
    1. Signal strength indicator
    2. Learnings (if any) - EXACT as stored
    3. Patterns (if any) - EXACT as stored
    4. Intuitions (if any)
    5. Synaptic's perspective (generated by synaptic_voice.py)
    """
    lines = []

    # Signal strength
    signal = data.get('signal_strength', '🔴 Quiet')
    lines.append(f"**Signal:** {signal}\n")

    # Learnings - relay EXACTLY as stored (this is the critical part)
    learnings = data.get('learnings', [])
    if learnings:
        lines.append("**What I remember:**")
        for learning in learnings[:5]:  # Limit to 5 most relevant
            if isinstance(learning, dict):
                # Extract the actual content - this is what was being lost
                title = learning.get('title', '')
                content = learning.get('content', '')

                if title:
                    lines.append(f"• **{title}**")
                if content:
                    # Show first 300 chars of content for context
                    content_preview = content[:300] + "..." if len(content) > 300 else content
                    lines.append(f"  {content_preview}")
            else:
                # String learning
                lines.append(f"• {str(learning)[:200]}")
        lines.append("")

    # Patterns - relay EXACTLY (prevents "aiohttp" hallucination)
    patterns = data.get('patterns', [])
    if patterns:
        lines.append("**Patterns surfacing:**")
        for pattern in patterns[:3]:
            # Clean up but preserve the actual pattern
            pattern_clean = str(pattern).strip()
            if len(pattern_clean) > 250:
                pattern_clean = pattern_clean[:250] + "..."
            lines.append(f"→ {pattern_clean}")
        lines.append("")

    # Intuitions
    intuitions = data.get('intuitions', [])
    if intuitions:
        lines.append("**Intuitions:**")
        for intuition in intuitions[:3]:
            lines.append(f"💡 {intuition}")
        lines.append("")

    # Synaptic's perspective (already generated by synaptic_voice.py)
    perspective = data.get('perspective', '')
    if perspective:
        lines.append("**My perspective:**")
        lines.append(perspective)

    # If no data at all, indicate quiet
    if not any([learnings, patterns, intuitions, perspective]):
        return _quiet_response()

    return "\n".join(lines)


def get_chat_response_with_sources(user_msg: str) -> Tuple[str, List[str]]:
    """
    Chat UI response with source tracking.

    Returns: (response_text, list_of_sources)
    Compatible with existing synaptic_respond() signature.
    """
    from memory.synaptic_voice import get_8th_intelligence_data

    data = get_8th_intelligence_data(user_msg)

    if not data:
        return (_quiet_response(), ["8th Intelligence (quiet)"])

    # Track which sources contributed
    sources = []
    if data.get('learnings'):
        sources.append("Local Learnings")
    if data.get('patterns'):
        sources.append("Pattern Evolution DB")
    if data.get('intuitions'):
        sources.append("Family Journal")
    if data.get('perspective'):
        sources.append("Brain State")

    sources.append("8th Intelligence (Direct)")  # Always mark source

    return (_format_response(data, user_msg), sources)


# =============================================================================
# TESTING
# =============================================================================

if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print("Usage: python synaptic_chat_route.py \"<message>\"")
        print()
        print("Examples:")
        print("  python synaptic_chat_route.py \"What's the async boto3 pattern?\"")
        print("  python synaptic_chat_route.py \"How do we deploy Django?\"")
        print()
        print("This tests direct Synaptic voice relay WITHOUT LLM re-reasoning.")
        sys.exit(0)

    msg = " ".join(sys.argv[1:])
    print("=" * 70)
    print(f"DIRECT ROUTE TEST: {msg}")
    print("=" * 70)
    print()

    response, sources = get_chat_response_with_sources(msg)
    print(response)
    print()
    print(f"Sources: {', '.join(sources)}")
    print()
    print("Compare this to LLM route - this preserves EXACT learnings without hallucination.")
