PEER_NAMES="mac1 mac2 mac3"
PEER_mac1="aarontjomsland@192.168.1.164"
PEER_mac2="aarontjomsland@192.168.1.183"
PEER_mac3="aarontjomsland@192.168.1.191"
CHIEF="mac1"

# MAC addresses for P6 Wake-on-LAN
MAC_mac1="5c:9b:a6:72:fa:57"
MAC_mac2="12:65:85:92:04:49"
MAC_mac3="e2:b7:98:c6:1d:ff"
