#!/bin/bash
# ============================================================================
# ZSF Bare-Except Gate — catches the bare-swallow anti-pattern
# ============================================================================
# R2 found 7 bare `except: pass` sites in the v6 competition engine that
# violate the Zero Silent Failures invariant. We are NOT importing v6 directly
# (we reimplement the IDEAS), so this gate makes sure that when S1/S2/S3/S4
# (or anyone) re-introduces a v6 pattern in our tree, the swallow is caught
# BEFORE it lands.
#
# How it works:
#   - Walks every tracked .py via Python AST (catches conditional / nested
#     handlers a plain grep would miss).
#   - Flags `except:` and `except Exception:` whose body is a single `pass`
#     (or only Pass / Constant / docstring — same swallow shape).
#   - Compares the current set of (path, exc-type) pairs against the
#     baseline at scripts/.zsf-bare-except-allowlist.txt.
#   - NEW pairs (a swallow in a path/type that wasn't present before) → FAIL.
#   - Lines may carry `# zsf-allow` or `# noqa: BLE001` to mark an audited
#     legitimate swallow — these are skipped by the scanner itself.
#
# The actual scanning is in scripts/zsf_bare_except_scan.py — kept separate
# so other gates / CI surfaces can reuse it.
#
# Usage:
#   scripts/check-zsf-bare-except.sh            # check (exit 0 / 1)
#   scripts/check-zsf-bare-except.sh --verbose  # show pass-line details
#   scripts/check-zsf-bare-except.sh --regen    # regen the allowlist (review!)
#
# Exit:
#   0 — current state matches allowlist (no new bare swallows)
#   1 — new bare-except violation detected, OR allowlist file missing
#   2 — internal error (Python missing, AST parse failed, refused scan path)
# ============================================================================

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"

VERBOSE=false
REGEN=false
for arg in "$@"; do
    case "$arg" in
        --verbose|-v) VERBOSE=true ;;
        --regen) REGEN=true ;;
    esac
done

ALLOWLIST="$SCRIPT_DIR/.zsf-bare-except-allowlist.txt"
SCANNER="$SCRIPT_DIR/zsf_bare_except_scan.py"

if [[ ! -f "$SCANNER" ]]; then
    echo "[zsf-gate] FAIL: scanner missing: $SCANNER" >&2
    exit 2
fi

PY="$REPO_DIR/.venv/bin/python3"
[[ ! -x "$PY" ]] && PY="$(command -v python3 || true)"
if [[ -z "$PY" ]]; then
    echo "[zsf-gate] FAIL: python3 not available" >&2
    exit 2
fi

# Run the AST scanner. SCAN_OUT carries one line per violation:
#   <rel-path>:<lineno>:<exc-type>
SCAN_OUT=$("$PY" "$SCANNER" "$REPO_DIR" 2>/tmp/zsf-gate-scan.err)
SCAN_RC=$?

if [[ "$SCAN_RC" -ne 0 ]]; then
    echo "[zsf-gate] FAIL: scanner errored (rc=$SCAN_RC)" >&2
    cat /tmp/zsf-gate-scan.err >&2 2>/dev/null || true
    exit 2
fi

# --regen: write a fresh allowlist with header preserved.
if [[ "$REGEN" == true ]]; then
    HEADER='# ZSF bare-except allowlist
#
# Format: <relative-path>:<lineno>:<exc-type>
#
# Generated by scripts/check-zsf-bare-except.sh on initial baseline.
#
# These are the legacy bare `except:` / `except Exception: pass` (or single-
# inert-body) sites that exist in the repo as of 2026-05-04. They are
# treated as the frozen ZSF baseline. NEW entries beyond this set will fail
# scripts/check-zsf-bare-except.sh.
#
# When the gate fails because an entry MOVED LINES (legitimate refactor,
# not a new swallow), regenerate this file via:
#     ./scripts/check-zsf-bare-except.sh --regen
# and review the diff before committing.
#
# When the gate fails because a NEW bare-except landed (R2 ZSF cleanup
# requirement on v6 patterns), the offender must:
# - log the failure to a counter / structured logger / health channel; or
# - swallow ONLY a tightly-scoped exception class with a comment justifying
#   why silence is correct (e.g. KeyboardInterrupt) — the pattern then is
#   no longer `except: pass`; or
# - mark the line `# zsf-allow` with a one-line justification (audited).
#
# DO NOT add entries here manually to silence the gate. Audit, then either
# fix the swallow (preferred) or mark the line `# zsf-allow`.
#
# Pairs are matched on (path, exc-type). Line numbers below are
# informational; legitimate refactors that move lines do NOT trip the gate.'
    {
        printf '%s\n' "$HEADER"
        printf '%s\n' "$SCAN_OUT"
    } > "$ALLOWLIST"
    COUNT=$(printf '%s\n' "$SCAN_OUT" | grep -cv '^[[:space:]]*$' || true)
    echo "[zsf-gate] regenerated $ALLOWLIST ($COUNT entries)"
    exit 0
fi

if [[ ! -f "$ALLOWLIST" ]]; then
    echo "[zsf-gate] FAIL: allowlist missing — run scripts/check-zsf-bare-except.sh --regen to create" >&2
    exit 1
fi

# Build sets of (path, exc-type) pairs. Drop line numbers from comparison —
# legitimate refactors that shift lines should not flip the gate. New
# (path, exc-type) pairs are the actual signal of new coupling.
ALLOW_PAIRS=$(grep -v '^[[:space:]]*#' "$ALLOWLIST" | grep -v '^[[:space:]]*$' \
    | awk -F: '{print $1":"$3}' | sort -u)
CURRENT_PAIRS=$(printf '%s\n' "$SCAN_OUT" | grep -v '^[[:space:]]*$' \
    | awk -F: '{print $1":"$3}' | sort -u)

NEW_PAIRS=$(comm -23 <(printf '%s\n' "$CURRENT_PAIRS") <(printf '%s\n' "$ALLOW_PAIRS"))

if [[ -z "$NEW_PAIRS" ]]; then
    if [[ "$VERBOSE" == true ]]; then
        TOTAL=$(printf '%s\n' "$CURRENT_PAIRS" | grep -cv '^[[:space:]]*$' || true)
        echo "[zsf-gate] PASS — $TOTAL allowed bare-except pairs, no new entries"
    fi
    exit 0
fi

NEW_COUNT=$(printf '%s\n' "$NEW_PAIRS" | grep -cv '^[[:space:]]*$' || true)
echo "[zsf-gate] FAIL — $NEW_COUNT new bare-except violation(s) (ZSF):" >&2
while IFS= read -r pair; do
    [[ -z "$pair" ]] && continue
    # Annotate the line number(s) where the new pair lives.
    LINES=$(printf '%s\n' "$SCAN_OUT" | awk -F: -v p="$pair" '$1":"$3==p {print $2}' | paste -sd, -)
    echo "  - $pair (lines: ${LINES:-?})" >&2
done <<<"$NEW_PAIRS"
echo "" >&2
echo "ZSF Bare-Except Gate violated. Options (in order of preference):" >&2
echo "  1. Fix the swallow: log to a counter / structured logger / health channel." >&2
echo "  2. Narrow the exception class (e.g. except KeyboardInterrupt:) — the" >&2
echo "     bare-swallow shape no longer applies and the gate clears." >&2
echo "  3. Add '# zsf-allow' or '# noqa: BLE001' to the except line with a" >&2
echo "     one-line justification — only after audit." >&2
echo "  See scripts/.zsf-bare-except-allowlist.txt header for policy." >&2
exit 1
