#!/bin/bash
# ============================================================================
# Multi-Fleet Extraction Contract — Forbidden-Direction Import Gate
# ============================================================================
# Phase 1 ("Stop the bleeding") of the mf extraction plan.
#
# Goal: freeze the current set of `from memory.* | from scripts.* | from tools.*`
# imports inside `multi-fleet/multifleet/` so the package doesn't grow MORE
# coupling to superrepo before the eventual extraction.
#
# How it works:
#   - Walks every .py under multi-fleet/multifleet/ via Python's `ast` module
#     (catches conditional/lazy imports inside functions — a plain grep would
#     miss the indented `from memory.* import …` calls).
#   - Compares the current set of (module, file) coupling pairs against the
#     baseline checked in at multi-fleet/.extraction-contract.allowlist.
#   - Pairs are matched on (module, file). Line numbers in the allowlist are
#     informational; legitimate refactors that move lines do NOT trip the gate.
#   - NEW pairs (forbidden module imported in a file that wasn't doing so
#     before) → FAIL.
#
# Usage:
#   scripts/check-mf-extraction-contract.sh           # check (exit 0 / 1)
#   scripts/check-mf-extraction-contract.sh --verbose # show full diff
#   scripts/check-mf-extraction-contract.sh --regen   # regenerate the
#                                                     # allowlist (review diff
#                                                     # before commit!)
#
# Exit:
#   0 — current state matches allowlist (no new forbidden coupling)
#   1 — new forbidden import detected, OR allowlist file missing
#   2 — internal error (Python missing, AST parse failed)
#
# See multi-fleet/EXTRACTION-CONTRACT.md for the full contract.
# ============================================================================

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"

VERBOSE=false
REGEN=false
for arg in "$@"; do
    case "$arg" in
        --verbose|-v) VERBOSE=true ;;
        --regen) REGEN=true ;;
    esac
done

ROOT="$REPO_DIR/multi-fleet/multifleet"
ALLOWLIST="$REPO_DIR/multi-fleet/.extraction-contract.allowlist"

if [[ ! -d "$ROOT" ]]; then
    echo "[contract] FAIL: $ROOT not found — multifleet package missing" >&2
    exit 2
fi

PY="$REPO_DIR/.venv/bin/python3"
[[ ! -x "$PY" ]] && PY="$(command -v python3 || true)"
if [[ -z "$PY" ]]; then
    echo "[contract] FAIL: python3 not available" >&2
    exit 2
fi

# Python AST scanner. Emits one line per forbidden import:
#   <module>:<rel-path-from-multi-fleet>:<lineno>
# rel-path is normalized so the allowlist is portable across machines.
SCAN_OUT=$("$PY" - "$ROOT" "$REPO_DIR/multi-fleet" <<'PY' 2>&1
import ast, os, sys

root = sys.argv[1]
base = sys.argv[2]
forbidden = ("memory", "scripts", "tools")

entries = []
errors = []
for dirpath, dirs, files in os.walk(root):
    if "__pycache__" in dirpath:
        continue
    for f in sorted(files):
        if not f.endswith(".py"):
            continue
        path = os.path.join(dirpath, f)
        try:
            with open(path, encoding="utf-8") as fh:
                src = fh.read()
        except OSError as exc:
            errors.append(f"read-fail:{path}:{exc}")
            continue
        try:
            tree = ast.parse(src, path)
        except SyntaxError as exc:
            errors.append(f"parse-fail:{path}:{exc}")
            continue
        rel = os.path.relpath(path, base)
        for node in ast.walk(tree):
            mods = []
            if isinstance(node, ast.ImportFrom):
                if node.module:
                    top = node.module.split(".")[0]
                    if top in forbidden:
                        mods.append(node.module)
            elif isinstance(node, ast.Import):
                for alias in node.names:
                    top = alias.name.split(".")[0]
                    if top in forbidden:
                        mods.append(alias.name)
            for mod in mods:
                entries.append((mod, rel, node.lineno))

if errors:
    # ZSF: surface parse/read failures explicitly. Any failure invalidates
    # the scan because we cannot prove no new import landed in a file we
    # could not parse.
    for err in errors:
        sys.stderr.write(f"[scan-error] {err}\n")
    sys.exit(2)

entries.sort()
for m, r, ln in entries:
    print(f"{m}:{r}:{ln}")
PY
)
SCAN_RC=$?

if [[ "$SCAN_RC" -ne 0 ]]; then
    echo "[contract] FAIL: scanner errored" >&2
    echo "$SCAN_OUT" >&2
    exit 2
fi

# --regen: write the allowlist (with header preserved) and exit.
if [[ "$REGEN" == true ]]; then
    HEADER='# multifleet → superrepo lazy-import allowlist
#
# Format: <module>:<relative-path-from-multi-fleet/>:<lineno>
#
# Generated by scripts/check-mf-extraction-contract.sh on initial baseline
# (Phase 1 — "Stop the bleeding"). See multi-fleet/EXTRACTION-CONTRACT.md.
#
# These are the lazy `from memory.* / scripts.* / tools.*` (or `import x`) calls
# that currently live INSIDE the multifleet package, treated as the frozen
# baseline. New entries beyond this set will fail
# scripts/check-mf-extraction-contract.sh.
#
# When the contract check fails because an entry MOVED LINES (legitimate
# refactor, not a new coupling), regenerate this file via:
#     ./scripts/check-mf-extraction-contract.sh --regen
# and review the diff before committing.
#
# When the contract check fails because a NEW import landed, the offender must:
# - either move the dependency in the OPPOSITE direction (have the consumer in
#   superrepo own the call) per Phase 2+ of the extraction plan, or
# - delete the new coupling.
#
# DO NOT add entries to this file manually to silence the gate. The gate exists
# to freeze drift, not to be edited around.'
    {
        printf '%s\n' "$HEADER"
        printf '%s\n' "$SCAN_OUT"
    } > "$ALLOWLIST"
    echo "[contract] regenerated $ALLOWLIST ($(echo "$SCAN_OUT" | wc -l | tr -d ' ') entries)"
    exit 0
fi

if [[ ! -f "$ALLOWLIST" ]]; then
    echo "[contract] FAIL: allowlist missing — run scripts/check-mf-extraction-contract.sh --regen to create" >&2
    exit 1
fi

# Build sets of (module, file) pairs. We deliberately drop line numbers from
# the comparison key — legitimate refactors that shift lines should not flip
# the gate. New (module, file) pairs are the actual signal of new coupling.
ALLOW_PAIRS=$(grep -v '^[[:space:]]*#' "$ALLOWLIST" | grep -v '^[[:space:]]*$' \
    | awk -F: '{print $1":"$2}' | sort -u)
CURRENT_PAIRS=$(printf '%s\n' "$SCAN_OUT" | grep -v '^[[:space:]]*$' \
    | awk -F: '{print $1":"$2}' | sort -u)

NEW_PAIRS=$(comm -23 <(printf '%s\n' "$CURRENT_PAIRS") <(printf '%s\n' "$ALLOW_PAIRS"))

if [[ -z "$NEW_PAIRS" ]]; then
    if [[ "$VERBOSE" == true ]]; then
        TOTAL=$(printf '%s\n' "$CURRENT_PAIRS" | wc -l | tr -d ' ')
        echo "[contract] PASS — $TOTAL allowed coupling pairs, no new entries"
    fi
    exit 0
fi

NEW_COUNT=$(printf '%s\n' "$NEW_PAIRS" | wc -l | tr -d ' ')
echo "[contract] FAIL — $NEW_COUNT new forbidden import(s) inside multi-fleet/multifleet/:" >&2
while IFS= read -r pair; do
    [[ -z "$pair" ]] && continue
    # Annotate the line number(s) where the new pair lives, so the operator
    # can navigate directly to the offender.
    LINES=$(printf '%s\n' "$SCAN_OUT" | awk -F: -v p="$pair" '$1":"$2==p {print $3}' | paste -sd, -)
    echo "  - $pair (lines: ${LINES:-?})" >&2
done <<<"$NEW_PAIRS"
echo "" >&2
echo "Multi-Fleet Extraction Contract violated. Options:" >&2
echo "  1. Remove the new import (preferred — invert the dependency)." >&2
echo "  2. If this is a legitimate Phase-2 refactor approved by Aaron," >&2
echo "     run: scripts/check-mf-extraction-contract.sh --regen" >&2
echo "     and commit the updated allowlist with the change." >&2
echo "  See multi-fleet/EXTRACTION-CONTRACT.md for context." >&2
exit 1
