#!/usr/bin/env python3
"""
Import panel pipeline data via REST API.

This script sends panel data directly to the production API endpoint,
bypassing the need for SSH/SSM access to the server.

Usage:
    python scripts/import_panels_via_api.py
    python scripts/import_panels_via_api.py --dry-run
"""

import json
import requests
import argparse
from datetime import datetime

API_BASE = "https://api.ersimulator.com/api/nasa/pipeline"

# Headers to authenticate as admin.ersimulator.com (internal tool)
HEADERS = {
    "Content-Type": "application/json",
    "Origin": "https://admin.ersimulator.com",
}


def import_page(page_slug: str, page_name: str, page_desc: str, panels: list, dry_run: bool = False):
    """Import a single page with all its panels."""
    url = f"{API_BASE}/pages/{page_slug}/"

    payload = {
        "name": page_name,
        "description": page_desc,
        "panels": panels,
    }

    if dry_run:
        print(f"\n[DRY RUN] Would POST to {url}")
        print(f"  Page: {page_name}")
        print(f"  Panels: {len(panels)}")
        for p in panels:
            print(f"    - {p['panel_id']}: {p['hover_name']}")
        return {"success": True, "dry_run": True}

    print(f"\nPOSTing to {url}...")
    print(f"  Page: {page_name}")
    print(f"  Panels: {len(panels)}")

    try:
        response = requests.post(url, json=payload, headers=HEADERS, timeout=30)
        response.raise_for_status()
        result = response.json()
        print(f"  ✓ Success: {result}")
        return result
    except requests.exceptions.RequestException as e:
        print(f"  ✗ Error: {e}")
        if hasattr(e, 'response') and e.response is not None:
            print(f"    Response: {e.response.text[:500]}")
        return {"success": False, "error": str(e)}


def main():
    parser = argparse.ArgumentParser(description="Import panel pipeline data via API")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be imported")
    args = parser.parse_args()

    print("=" * 60)
    print("Panel Pipeline API Import")
    print("=" * 60)
    print(f"API Base: {API_BASE}")
    print(f"Timestamp: {datetime.now().isoformat()}")

    # =========================================================================
    # AI TESTER PAGE - 20 Panels
    # =========================================================================
    ai_tester_panels = [
        # LEFT COLUMN - 7 Panels
        {
            "panel_id": "results-overview",
            "hover_name": "Results Overview",
            "description": "Session outcome and performance summary with score breakdown",
            "frontend_component": "components/ai-testing-characters-page.tsx",
            "frontend_hook": "useOutcome(sessionId)",
            "frontend_hook_status": "working",
            "api_client_file": "lib/api/progress.ts",
            "api_client_function": "fetchOutcome(sessionId)",
            "api_client_status": "working",
            "api_endpoint": "/api/progress/outcome/{session_id}/",
            "api_method": "GET",
            "api_auth_type": "admin_token",
            "api_request_status": "200",
            "api_response_format": "{score_percent, diagnosis_correct, events[], timing_breakdown, critical_actions_hit}",
            "backend_app": "progress",
            "backend_urls_file": "backend/progress/urls.py",
            "backend_urls_status": "route_exists",
            "backend_views_file": "backend/progress/views.py",
            "backend_view_function": "outcome_view",
            "backend_views_status": "working",
            "backend_serializer": "OutcomeSerializer in backend/progress/serializers.py",
            "backend_serializer_status": "working",
            "backend_models": "CaseRun, CaseRunEvent, CaseRunScoring",
            "backend_models_status": "working",
            "db_has_data": "yes",
            "db_record_count": "500+ CaseRun records",
            "pipeline_status": "fully_connected",
            "data_source": "live_api",
            "verified_by": "aaron",
            "blocking_issue": "",
            "next_action": "Done",
            "priority": "P3",
            "environment_zone": "internal_lab",
            "error_count": 0,
        },
        {
            "panel_id": "voice-simulator",
            "hover_name": "Voice Simulator",
            "description": "Live patient interaction interface using OpenAI Realtime API",
            "frontend_component": "components/ai-testing-characters-page.tsx",
            "frontend_hook": "useRealtimeVoice(sessionConfig)",
            "frontend_hook_status": "working",
            "api_client_file": "lib/voice/realtime-client.ts",
            "api_client_function": "connectToRealtimeAPI()",
            "api_client_status": "working",
            "api_endpoint": "wss://api.openai.com/v1/realtime",
            "api_method": "GET",
            "api_auth_type": "openai_api_key",
            "api_request_status": "200",
            "api_response_format": "WebSocket stream: audio chunks, transcripts, function calls",
            "backend_app": "external",
            "backend_urls_file": "N/A - External OpenAI API",
            "backend_urls_status": "route_exists",
            "backend_views_file": "N/A - External OpenAI API",
            "backend_view_function": "OpenAI Realtime WebSocket",
            "backend_views_status": "working",
            "backend_serializer": "N/A - WebSocket protocol",
            "backend_serializer_status": "not_needed",
            "backend_models": "N/A - External service",
            "backend_models_status": "not_needed",
            "db_has_data": "not_checked",
            "db_record_count": "N/A - External",
            "pipeline_status": "fully_connected",
            "data_source": "external_api",
            "verified_by": "aaron",
            "blocking_issue": "",
            "next_action": "Done",
            "priority": "P3",
            "environment_zone": "internal_lab",
            "error_count": 0,
        },
        {
            "panel_id": "status-test-runs",
            "hover_name": "Test Runs Today",
            "description": "Count of AI tester runs executed today with comparison to yesterday",
            "frontend_component": "components/ai-testing-characters-page.tsx",
            "frontend_hook": "useTestRuns({ today: true })",
            "frontend_hook_status": "working",
            "api_client_file": "lib/api/tester.ts",
            "api_client_function": "fetchTestRuns({ filter: 'today' })",
            "api_client_status": "working",
            "api_endpoint": "/api/simtester/runs/?today=true",
            "api_method": "GET",
            "api_auth_type": "admin_token",
            "api_request_status": "200",
            "api_response_format": "{runs: [], count: number, yesterday_count: number}",
            "backend_app": "simtester",
            "backend_urls_file": "backend/simtester/urls.py",
            "backend_urls_status": "route_exists",
            "backend_views_file": "backend/simtester/views.py",
            "backend_view_function": "test_runs_list_view",
            "backend_views_status": "working",
            "backend_serializer": "TestRunSerializer in backend/simtester/serializers.py",
            "backend_serializer_status": "working",
            "backend_models": "TestRun, CaseRun (filtered by is_test_run=True)",
            "backend_models_status": "working",
            "db_has_data": "yes",
            "db_record_count": "~100 test runs",
            "pipeline_status": "fully_connected",
            "data_source": "live_api",
            "verified_by": "atlas",
            "blocking_issue": "",
            "next_action": "Done",
            "priority": "P3",
            "environment_zone": "internal_lab",
            "error_count": 0,
        },
        {
            "panel_id": "status-issues",
            "hover_name": "Issues Found",
            "description": "Current issues detected during test runs requiring review",
            "frontend_component": "components/ai-testing-characters-page.tsx",
            "frontend_hook": "useState<Issue[]>([])",
            "frontend_hook_status": "working",
            "api_client_file": "N/A - Local state only",
            "api_client_function": "N/A - Local state only",
            "api_client_status": "not_needed",
            "api_endpoint": "/api/simtester/issues/",
            "api_method": "GET",
            "api_auth_type": "admin_token",
            "api_request_status": "not_tested",
            "api_response_format": "{issues: [{id, severity, category, title, case_id, resolved}], summary: {high, medium, low}}",
            "backend_app": "simtester",
            "backend_urls_file": "backend/simtester/urls.py",
            "backend_urls_status": "route_missing",
            "backend_views_file": "backend/simtester/views.py",
            "backend_view_function": "test_issues_view",
            "backend_views_status": "not_implemented",
            "backend_serializer": "TestIssueSerializer",
            "backend_serializer_status": "not_implemented",
            "backend_models": "TestIssue (NEW - needs creation)",
            "backend_models_status": "not_implemented",
            "db_has_data": "no",
            "db_record_count": "0 - Model not created",
            "pipeline_status": "mock_fallback",
            "data_source": "local_state",
            "verified_by": "",
            "blocking_issue": "TestIssue model and endpoint not implemented",
            "next_action": "Create TestIssue model in backend/simtester/models.py",
            "priority": "P2",
            "environment_zone": "internal_lab",
            "error_count": 0,
        },
        {
            "panel_id": "status-cases",
            "hover_name": "Cases Covered",
            "description": "Case coverage progress showing tested vs total cases",
            "frontend_component": "components/ai-testing-characters-page.tsx",
            "frontend_hook": "useNasaCases()",
            "frontend_hook_status": "working",
            "api_client_file": "lib/api/nasa-lab.ts",
            "api_client_function": "fetchNasaCases()",
            "api_client_status": "working",
            "api_endpoint": "/api/controlpanel/nasa/cases/",
            "api_method": "GET",
            "api_auth_type": "admin_token",
            "api_request_status": "200",
            "api_response_format": "{cases: [{case_id, title, is_active, last_tested}], total: number, tested: number}",
            "backend_app": "controlpanel",
            "backend_urls_file": "backend/controlpanel/urls.py",
            "backend_urls_status": "route_exists",
            "backend_views_file": "backend/controlpanel/api_views.py",
            "backend_view_function": "cases_list_view",
            "backend_views_status": "working",
            "backend_serializer": "Inline dict serialization",
            "backend_serializer_status": "working",
            "backend_models": "SimCase from sim app",
            "backend_models_status": "working",
            "db_has_data": "yes",
            "db_record_count": "50+ SimCase records",
            "pipeline_status": "fully_connected",
            "data_source": "live_api",
            "verified_by": "aaron",
            "blocking_issue": "",
            "next_action": "Done",
            "priority": "P3",
            "environment_zone": "internal_lab",
            "error_count": 0,
        },
        {
            "panel_id": "active-persona",
            "hover_name": "Active Persona",
            "description": "Currently active AI testing persona configuration display",
            "frontend_component": "components/ai-testing-characters-page.tsx",
            "frontend_hook": "useActivePersona()",
            "frontend_hook_status": "working",
            "api_client_file": "lib/api/tester.ts",
            "api_client_function": "fetchActivePersona()",
            "api_client_status": "working",
            "api_endpoint": "/api/simtester/persona/active/",
            "api_method": "GET",
            "api_auth_type": "admin_token",
            "api_request_status": "200",
            "api_response_format": "{persona_id, name, description, traits[], experience_level, specialty}",
            "backend_app": "simtester",
            "backend_urls_file": "backend/simtester/urls.py",
            "backend_urls_status": "route_exists",
            "backend_views_file": "backend/simtester/views.py",
            "backend_view_function": "active_persona_view",
            "backend_views_status": "working",
            "backend_serializer": "PersonaSerializer",
            "backend_serializer_status": "working",
            "backend_models": "TesterPersona",
            "backend_models_status": "working",
            "db_has_data": "yes",
            "db_record_count": "10+ personas",
            "pipeline_status": "fully_connected",
            "data_source": "live_api",
            "verified_by": "aaron",
            "blocking_issue": "",
            "next_action": "Done",
            "priority": "P3",
            "environment_zone": "internal_lab",
            "error_count": 0,
        },
        {
            "panel_id": "testing-metrics",
            "hover_name": "Testing Metrics",
            "description": "Key performance indicators for AI testing effectiveness",
            "frontend_component": "components/ai-testing-characters-page.tsx",
            "frontend_hook": "useTestingMetrics()",
            "frontend_hook_status": "working",
            "api_client_file": "lib/api/tester.ts",
            "api_client_function": "fetchTestingMetrics()",
            "api_client_status": "working",
            "api_endpoint": "/api/simtester/metrics/",
            "api_method": "GET",
            "api_auth_type": "admin_token",
            "api_request_status": "200",
            "api_response_format": "{avg_score, pass_rate, avg_duration, issues_found_rate}",
            "backend_app": "simtester",
            "backend_urls_file": "backend/simtester/urls.py",
            "backend_urls_status": "route_exists",
            "backend_views_file": "backend/simtester/views.py",
            "backend_view_function": "testing_metrics_view",
            "backend_views_status": "working",
            "backend_serializer": "Inline dict",
            "backend_serializer_status": "working",
            "backend_models": "CaseRun, TestRun aggregations",
            "backend_models_status": "working",
            "db_has_data": "yes",
            "db_record_count": "Aggregated from runs",
            "pipeline_status": "fully_connected",
            "data_source": "live_api",
            "verified_by": "atlas",
            "blocking_issue": "",
            "next_action": "Done",
            "priority": "P3",
            "environment_zone": "internal_lab",
            "error_count": 0,
        },
        # CENTER COLUMN - 6 Panels
        {
            "panel_id": "live-transcript",
            "hover_name": "Live Transcript",
            "description": "Real-time conversation transcript during active simulation",
            "frontend_component": "components/ai-testing-characters-page.tsx",
            "frontend_hook": "useConversationStream(sessionId)",
            "frontend_hook_status": "working",
            "api_client_file": "lib/api/sessions.ts",
            "api_client_function": "streamConversation(sessionId)",
            "api_client_status": "working",
            "api_endpoint": "/api/sessions/{session_id}/transcript/stream/",
            "api_method": "GET",
            "api_auth_type": "admin_token",
            "api_request_status": "200",
            "api_response_format": "SSE stream: {role, content, timestamp, speaker}",
            "backend_app": "sessions",
            "backend_urls_file": "backend/sessions/urls.py",
            "backend_urls_status": "route_exists",
            "backend_views_file": "backend/sessions/views.py",
            "backend_view_function": "transcript_stream_view",
            "backend_views_status": "working",
            "backend_serializer": "SSE format",
            "backend_serializer_status": "working",
            "backend_models": "SessionMessage",
            "backend_models_status": "working",
            "db_has_data": "yes",
            "db_record_count": "Real-time stream",
            "pipeline_status": "fully_connected",
            "data_source": "live_api",
            "verified_by": "aaron",
            "blocking_issue": "",
            "next_action": "Done",
            "priority": "P3",
            "environment_zone": "internal_lab",
            "error_count": 0,
        },
        {
            "panel_id": "session-controls",
            "hover_name": "Session Controls",
            "description": "Start, stop, pause controls for AI testing sessions",
            "frontend_component": "components/ai-testing-characters-page.tsx",
            "frontend_hook": "useSessionControls()",
            "frontend_hook_status": "working",
            "api_client_file": "lib/api/sessions.ts",
            "api_client_function": "startSession(), stopSession(), pauseSession()",
            "api_client_status": "working",
            "api_endpoint": "/api/sessions/control/",
            "api_method": "POST",
            "api_auth_type": "admin_token",
            "api_request_status": "200",
            "api_response_format": "{action_taken, session_id, status}",
            "backend_app": "sessions",
            "backend_urls_file": "backend/sessions/urls.py",
            "backend_urls_status": "route_exists",
            "backend_views_file": "backend/sessions/views.py",
            "backend_view_function": "session_control_view",
            "backend_views_status": "working",
            "backend_serializer": "Inline dict",
            "backend_serializer_status": "working",
            "backend_models": "SimSession",
            "backend_models_status": "working",
            "db_has_data": "yes",
            "db_record_count": "Active sessions",
            "pipeline_status": "fully_connected",
            "data_source": "live_api",
            "verified_by": "aaron",
            "blocking_issue": "",
            "next_action": "Done",
            "priority": "P3",
            "environment_zone": "internal_lab",
            "error_count": 0,
        },
        {
            "panel_id": "case-selector",
            "hover_name": "Case Selector",
            "description": "Case selection dropdown for AI tester runs",
            "frontend_component": "components/ai-testing-characters-page.tsx",
            "frontend_hook": "useCases()",
            "frontend_hook_status": "working",
            "api_client_file": "lib/api/cases.ts",
            "api_client_function": "fetchCases()",
            "api_client_status": "working",
            "api_endpoint": "/api/sim/cases/",
            "api_method": "GET",
            "api_auth_type": "admin_token",
            "api_request_status": "200",
            "api_response_format": "{cases: [{case_id, title, category, difficulty}]}",
            "backend_app": "sim",
            "backend_urls_file": "backend/sim/urls.py",
            "backend_urls_status": "route_exists",
            "backend_views_file": "backend/sim/views.py",
            "backend_view_function": "cases_list_view",
            "backend_views_status": "working",
            "backend_serializer": "SimCaseSerializer",
            "backend_serializer_status": "working",
            "backend_models": "SimCase",
            "backend_models_status": "working",
            "db_has_data": "yes",
            "db_record_count": "50+ cases",
            "pipeline_status": "fully_connected",
            "data_source": "live_api",
            "verified_by": "aaron",
            "blocking_issue": "",
            "next_action": "Done",
            "priority": "P3",
            "environment_zone": "internal_lab",
            "error_count": 0,
        },
        {
            "panel_id": "simulation-state",
            "hover_name": "Simulation State",
            "description": "Current simulation state and patient vitals display",
            "frontend_component": "components/ai-testing-characters-page.tsx",
            "frontend_hook": "useSimulationState(sessionId)",
            "frontend_hook_status": "working",
            "api_client_file": "lib/api/sim.ts",
            "api_client_function": "fetchSimState(sessionId)",
            "api_client_status": "working",
            "api_endpoint": "/api/sim/sessions/{session_id}/state/",
            "api_method": "GET",
            "api_auth_type": "admin_token",
            "api_request_status": "200",
            "api_response_format": "{vitals: {hr, bp, spo2, rr}, phase, elapsed_time, interventions[]}",
            "backend_app": "sim",
            "backend_urls_file": "backend/sim/urls.py",
            "backend_urls_status": "route_exists",
            "backend_views_file": "backend/sim/views.py",
            "backend_view_function": "session_state_view",
            "backend_views_status": "working",
            "backend_serializer": "SessionStateSerializer",
            "backend_serializer_status": "working",
            "backend_models": "SimSession, SimSessionState",
            "backend_models_status": "working",
            "db_has_data": "yes",
            "db_record_count": "Per-session state",
            "pipeline_status": "fully_connected",
            "data_source": "live_api",
            "verified_by": "atlas",
            "blocking_issue": "",
            "next_action": "Done",
            "priority": "P3",
            "environment_zone": "internal_lab",
            "error_count": 0,
        },
        {
            "panel_id": "function-calls",
            "hover_name": "Function Calls",
            "description": "Real-time log of AI function calls during simulation",
            "frontend_component": "components/ai-testing-characters-page.tsx",
            "frontend_hook": "useFunctionCalls(sessionId)",
            "frontend_hook_status": "working",
            "api_client_file": "lib/api/sessions.ts",
            "api_client_function": "fetchFunctionCalls(sessionId)",
            "api_client_status": "working",
            "api_endpoint": "/api/sessions/{session_id}/function-calls/",
            "api_method": "GET",
            "api_auth_type": "admin_token",
            "api_request_status": "200",
            "api_response_format": "{calls: [{function_name, arguments, result, timestamp}]}",
            "backend_app": "sessions",
            "backend_urls_file": "backend/sessions/urls.py",
            "backend_urls_status": "route_exists",
            "backend_views_file": "backend/sessions/views.py",
            "backend_view_function": "function_calls_view",
            "backend_views_status": "working",
            "backend_serializer": "FunctionCallSerializer",
            "backend_serializer_status": "working",
            "backend_models": "FunctionCall",
            "backend_models_status": "working",
            "db_has_data": "yes",
            "db_record_count": "Per-session calls",
            "pipeline_status": "fully_connected",
            "data_source": "live_api",
            "verified_by": "aaron",
            "blocking_issue": "",
            "next_action": "Done",
            "priority": "P3",
            "environment_zone": "internal_lab",
            "error_count": 0,
        },
        {
            "panel_id": "audio-waveform",
            "hover_name": "Audio Waveform",
            "description": "Visual representation of voice audio during simulation",
            "frontend_component": "components/ai-testing-characters-page.tsx",
            "frontend_hook": "useAudioVisualization(stream)",
            "frontend_hook_status": "working",
            "api_client_file": "N/A - Browser Audio API",
            "api_client_function": "Web Audio API visualization",
            "api_client_status": "not_needed",
            "api_endpoint": "N/A - Client-side only",
            "api_method": "GET",
            "api_auth_type": "none",
            "api_request_status": "200",
            "api_response_format": "N/A - Local audio stream",
            "backend_app": "N/A",
            "backend_urls_file": "N/A",
            "backend_urls_status": "not_checked",
            "backend_views_file": "N/A",
            "backend_view_function": "N/A",
            "backend_views_status": "not_needed",
            "backend_serializer": "N/A",
            "backend_serializer_status": "not_needed",
            "backend_models": "N/A",
            "backend_models_status": "not_needed",
            "db_has_data": "not_checked",
            "db_record_count": "N/A",
            "pipeline_status": "fully_connected",
            "data_source": "local_state",
            "verified_by": "aaron",
            "blocking_issue": "",
            "next_action": "Done",
            "priority": "P3",
            "environment_zone": "internal_lab",
            "error_count": 0,
        },
        # RIGHT COLUMN - 7 Panels
        {
            "panel_id": "persona-selector",
            "hover_name": "Persona Selector",
            "description": "Select AI tester persona for test runs",
            "frontend_component": "components/ai-testing-characters-page.tsx",
            "frontend_hook": "usePersonas()",
            "frontend_hook_status": "working",
            "api_client_file": "lib/api/tester.ts",
            "api_client_function": "fetchPersonas()",
            "api_client_status": "working",
            "api_endpoint": "/api/controlpanel/nasa/personas/",
            "api_method": "GET",
            "api_auth_type": "admin_token",
            "api_request_status": "200",
            "api_response_format": "{personas: [{id, name, description, is_active}]}",
            "backend_app": "controlpanel",
            "backend_urls_file": "backend/controlpanel/urls.py",
            "backend_urls_status": "route_exists",
            "backend_views_file": "backend/controlpanel/api_views.py",
            "backend_view_function": "personas_list_view",
            "backend_views_status": "working",
            "backend_serializer": "PersonaSerializer",
            "backend_serializer_status": "working",
            "backend_models": "FeedbackPersona",
            "backend_models_status": "working",
            "db_has_data": "yes",
            "db_record_count": "10+ personas",
            "pipeline_status": "fully_connected",
            "data_source": "live_api",
            "verified_by": "aaron",
            "blocking_issue": "",
            "next_action": "Done",
            "priority": "P3",
            "environment_zone": "internal_lab",
            "error_count": 0,
        },
        {
            "panel_id": "test-configuration",
            "hover_name": "Test Configuration",
            "description": "Configure AI tester parameters and behaviors",
            "frontend_component": "components/ai-testing-characters-page.tsx",
            "frontend_hook": "useTestConfig()",
            "frontend_hook_status": "working",
            "api_client_file": "lib/api/tester.ts",
            "api_client_function": "fetchTestConfig(), updateTestConfig()",
            "api_client_status": "working",
            "api_endpoint": "/api/simtester/config/",
            "api_method": "GET",
            "api_auth_type": "admin_token",
            "api_request_status": "200",
            "api_response_format": "{continuous_mode, max_runs, delay_between_runs, target_cases[]}",
            "backend_app": "simtester",
            "backend_urls_file": "backend/simtester/urls.py",
            "backend_urls_status": "route_exists",
            "backend_views_file": "backend/simtester/views.py",
            "backend_view_function": "test_config_view",
            "backend_views_status": "working",
            "backend_serializer": "TestConfigSerializer",
            "backend_serializer_status": "working",
            "backend_models": "TesterConfig",
            "backend_models_status": "working",
            "db_has_data": "yes",
            "db_record_count": "1 config record",
            "pipeline_status": "fully_connected",
            "data_source": "live_api",
            "verified_by": "aaron",
            "blocking_issue": "",
            "next_action": "Done",
            "priority": "P3",
            "environment_zone": "internal_lab",
            "error_count": 0,
        },
        {
            "panel_id": "improvement-suggestions",
            "hover_name": "AI Improvement Suggestions",
            "description": "AI-generated suggestions for character behavior improvements",
            "frontend_component": "components/ai-testing-characters-page.tsx",
            "frontend_hook": "useImprovementSuggestions(sessionId)",
            "frontend_hook_status": "working",
            "api_client_file": "lib/api/tester.ts",
            "api_client_function": "fetchSuggestions(sessionId)",
            "api_client_status": "working",
            "api_endpoint": "/api/controlpanel/nasa/ai-feedback/{case_id}/",
            "api_method": "GET",
            "api_auth_type": "admin_token",
            "api_request_status": "200",
            "api_response_format": "{suggestions: [{id, slider_name, current_value, suggested_value, rationale}]}",
            "backend_app": "controlpanel",
            "backend_urls_file": "backend/controlpanel/urls.py",
            "backend_urls_status": "route_exists",
            "backend_views_file": "backend/controlpanel/api_views.py",
            "backend_view_function": "ai_feedback_list_view",
            "backend_views_status": "working",
            "backend_serializer": "AIFeedbackSerializer",
            "backend_serializer_status": "working",
            "backend_models": "AITesterFeedback",
            "backend_models_status": "working",
            "db_has_data": "yes",
            "db_record_count": "100+ feedback records",
            "pipeline_status": "fully_connected",
            "data_source": "live_api",
            "verified_by": "atlas",
            "blocking_issue": "",
            "next_action": "Done",
            "priority": "P3",
            "environment_zone": "internal_lab",
            "error_count": 0,
        },
        {
            "panel_id": "test-history",
            "hover_name": "Test History",
            "description": "Historical list of AI test runs with results",
            "frontend_component": "components/ai-testing-characters-page.tsx",
            "frontend_hook": "useTestHistory({ limit: 50 })",
            "frontend_hook_status": "working",
            "api_client_file": "lib/api/tester.ts",
            "api_client_function": "fetchTestHistory()",
            "api_client_status": "working",
            "api_endpoint": "/api/simtester/runs/",
            "api_method": "GET",
            "api_auth_type": "admin_token",
            "api_request_status": "200",
            "api_response_format": "{runs: [{id, case_id, persona_id, score, created_at, status}]}",
            "backend_app": "simtester",
            "backend_urls_file": "backend/simtester/urls.py",
            "backend_urls_status": "route_exists",
            "backend_views_file": "backend/simtester/views.py",
            "backend_view_function": "test_runs_list_view",
            "backend_views_status": "working",
            "backend_serializer": "TestRunSerializer",
            "backend_serializer_status": "working",
            "backend_models": "CaseRun (is_test_run=True)",
            "backend_models_status": "working",
            "db_has_data": "yes",
            "db_record_count": "100+ test runs",
            "pipeline_status": "fully_connected",
            "data_source": "live_api",
            "verified_by": "aaron",
            "blocking_issue": "",
            "next_action": "Done",
            "priority": "P3",
            "environment_zone": "internal_lab",
            "error_count": 0,
        },
        {
            "panel_id": "continuous-mode-toggle",
            "hover_name": "Continuous Mode Toggle",
            "description": "Toggle for enabling continuous AI testing mode",
            "frontend_component": "components/ai-testing-characters-page.tsx",
            "frontend_hook": "useContinuousMode()",
            "frontend_hook_status": "working",
            "api_client_file": "lib/api/tester.ts",
            "api_client_function": "toggleContinuousMode()",
            "api_client_status": "working",
            "api_endpoint": "/api/simtester/continuous/toggle/",
            "api_method": "POST",
            "api_auth_type": "admin_token",
            "api_request_status": "200",
            "api_response_format": "{enabled: boolean, runs_remaining: number}",
            "backend_app": "simtester",
            "backend_urls_file": "backend/simtester/urls.py",
            "backend_urls_status": "route_exists",
            "backend_views_file": "backend/simtester/views.py",
            "backend_view_function": "continuous_mode_toggle_view",
            "backend_views_status": "working",
            "backend_serializer": "Inline dict",
            "backend_serializer_status": "working",
            "backend_models": "TesterConfig",
            "backend_models_status": "working",
            "db_has_data": "yes",
            "db_record_count": "1 config",
            "pipeline_status": "fully_connected",
            "data_source": "live_api",
            "verified_by": "aaron",
            "blocking_issue": "",
            "next_action": "Done",
            "priority": "P3",
            "environment_zone": "internal_lab",
            "error_count": 0,
        },
        {
            "panel_id": "special-mission",
            "hover_name": "Special Mission",
            "description": "Special mission panel for targeted testing scenarios",
            "frontend_component": "components/ai-testing-characters-page.tsx",
            "frontend_hook": "useSpecialMission()",
            "frontend_hook_status": "working",
            "api_client_file": "lib/api/nasa-lab.ts",
            "api_client_function": "fetchSpecialMission()",
            "api_client_status": "working",
            "api_endpoint": "/api/controlpanel/nasa/special-mission/config/",
            "api_method": "GET",
            "api_auth_type": "admin_token",
            "api_request_status": "200",
            "api_response_format": "{enabled: bool, mission_count: number, modifications: []}",
            "backend_app": "controlpanel",
            "backend_urls_file": "backend/controlpanel/urls.py",
            "backend_urls_status": "route_exists",
            "backend_views_file": "backend/controlpanel/api_views.py",
            "backend_view_function": "special_mission_config_view",
            "backend_views_status": "working",
            "backend_serializer": "Inline dict",
            "backend_serializer_status": "working",
            "backend_models": "SpecialMissionConfig, CharacterModification",
            "backend_models_status": "working",
            "db_has_data": "yes",
            "db_record_count": "1 config + modifications",
            "pipeline_status": "fully_connected",
            "data_source": "live_api",
            "verified_by": "atlas",
            "blocking_issue": "",
            "next_action": "Done",
            "priority": "P3",
            "environment_zone": "internal_lab",
            "error_count": 0,
        },
        {
            "panel_id": "error-log",
            "hover_name": "Error Log",
            "description": "Recent errors and warnings from AI testing system",
            "frontend_component": "components/ai-testing-characters-page.tsx",
            "frontend_hook": "useDebugEvents({ type: 'error' })",
            "frontend_hook_status": "working",
            "api_client_file": "lib/api/debug.ts",
            "api_client_function": "fetchDebugEvents({ type: 'error' })",
            "api_client_status": "working",
            "api_endpoint": "/api/controlpanel/nasa/debug-events/",
            "api_method": "GET",
            "api_auth_type": "admin_token",
            "api_request_status": "200",
            "api_response_format": "{events: [{id, type, message, stack_trace, created_at}]}",
            "backend_app": "controlpanel",
            "backend_urls_file": "backend/controlpanel/urls.py",
            "backend_urls_status": "route_exists",
            "backend_views_file": "backend/controlpanel/api_views.py",
            "backend_view_function": "debug_events_view",
            "backend_views_status": "working",
            "backend_serializer": "DebugEventSerializer",
            "backend_serializer_status": "working",
            "backend_models": "DebugEvent",
            "backend_models_status": "working",
            "db_has_data": "yes",
            "db_record_count": "1000+ events",
            "pipeline_status": "fully_connected",
            "data_source": "live_api",
            "verified_by": "aaron",
            "blocking_issue": "",
            "next_action": "Done",
            "priority": "P3",
            "environment_zone": "internal_lab",
            "error_count": 0,
        },
    ]

    # =========================================================================
    # DASHBOARD OVERVIEW PAGE - 8 Panels
    # =========================================================================
    dashboard_panels = [
        {
            "panel_id": "quick-stats",
            "hover_name": "Quick Stats",
            "description": "Quick overview statistics for the dashboard",
            "frontend_component": "components/dashboard-overview.tsx",
            "frontend_hook": "useQuickStats()",
            "frontend_hook_status": "working",
            "api_client_file": "lib/api/nasa-lab.ts",
            "api_client_function": "fetchQuickStats()",
            "api_client_status": "working",
            "api_endpoint": "/api/controlpanel/nasa/dashboard/",
            "api_method": "GET",
            "api_auth_type": "admin_token",
            "api_request_status": "200",
            "api_response_format": "{total_users, active_sessions, cases_available, avg_score}",
            "backend_app": "controlpanel",
            "backend_urls_file": "backend/controlpanel/urls.py",
            "backend_urls_status": "route_exists",
            "backend_views_file": "backend/controlpanel/api_views.py",
            "backend_view_function": "dashboard_view",
            "backend_views_status": "working",
            "backend_serializer": "Inline dict",
            "backend_serializer_status": "working",
            "backend_models": "User, SimSession, SimCase aggregates",
            "backend_models_status": "working",
            "db_has_data": "yes",
            "db_record_count": "Aggregated counts",
            "pipeline_status": "fully_connected",
            "data_source": "live_api",
            "verified_by": "aaron",
            "blocking_issue": "",
            "next_action": "Done",
            "priority": "P3",
            "environment_zone": "internal_lab",
            "error_count": 0,
        },
        {
            "panel_id": "character-interactions",
            "hover_name": "Character Interactions",
            "description": "Statistics on character interactions within simulations",
            "frontend_component": "components/dashboard-overview.tsx",
            "frontend_hook": "useCharacterInteractions()",
            "frontend_hook_status": "working",
            "api_client_file": "lib/api/nasa-lab.ts",
            "api_client_function": "fetchCharacterInteractions()",
            "api_client_status": "working",
            "api_endpoint": "/api/controlpanel/nasa/dashboard/character-interactions/",
            "api_method": "GET",
            "api_auth_type": "admin_token",
            "api_request_status": "200",
            "api_response_format": "{patient: {total, avg_per_session}, nurse: {total, avg_per_session}}",
            "backend_app": "controlpanel",
            "backend_urls_file": "backend/controlpanel/urls.py",
            "backend_urls_status": "route_exists",
            "backend_views_file": "backend/controlpanel/api_views.py",
            "backend_view_function": "dashboard_character_interactions_view",
            "backend_views_status": "working",
            "backend_serializer": "Inline dict",
            "backend_serializer_status": "working",
            "backend_models": "SessionMessage aggregates",
            "backend_models_status": "working",
            "db_has_data": "yes",
            "db_record_count": "Aggregated from messages",
            "pipeline_status": "fully_connected",
            "data_source": "live_api",
            "verified_by": "aaron",
            "blocking_issue": "",
            "next_action": "Done",
            "priority": "P3",
            "environment_zone": "internal_lab",
            "error_count": 0,
        },
        {
            "panel_id": "character-distribution",
            "hover_name": "Character Distribution",
            "description": "Distribution of character usage across sessions",
            "frontend_component": "components/dashboard-overview.tsx",
            "frontend_hook": "useCharacterDistribution()",
            "frontend_hook_status": "working",
            "api_client_file": "lib/api/nasa-lab.ts",
            "api_client_function": "fetchCharacterDistribution()",
            "api_client_status": "working",
            "api_endpoint": "/api/controlpanel/nasa/dashboard/character-distribution/",
            "api_method": "GET",
            "api_auth_type": "admin_token",
            "api_request_status": "200",
            "api_response_format": "{distribution: [{character, count, percentage}]}",
            "backend_app": "controlpanel",
            "backend_urls_file": "backend/controlpanel/urls.py",
            "backend_urls_status": "route_exists",
            "backend_views_file": "backend/controlpanel/api_views.py",
            "backend_view_function": "dashboard_character_distribution_view",
            "backend_views_status": "working",
            "backend_serializer": "Inline dict",
            "backend_serializer_status": "working",
            "backend_models": "SessionMessage aggregates",
            "backend_models_status": "working",
            "db_has_data": "yes",
            "db_record_count": "Aggregated",
            "pipeline_status": "fully_connected",
            "data_source": "live_api",
            "verified_by": "atlas",
            "blocking_issue": "",
            "next_action": "Done",
            "priority": "P3",
            "environment_zone": "internal_lab",
            "error_count": 0,
        },
        {
            "panel_id": "system-health",
            "hover_name": "System Health",
            "description": "Overall system health status with service checks",
            "frontend_component": "components/dashboard-overview.tsx",
            "frontend_hook": "useSystemHealth()",
            "frontend_hook_status": "working",
            "api_client_file": "lib/api/nasa-lab.ts",
            "api_client_function": "fetchSystemHealth()",
            "api_client_status": "working",
            "api_endpoint": "/api/controlpanel/nasa/dashboard/system-health/",
            "api_method": "GET",
            "api_auth_type": "admin_token",
            "api_request_status": "200",
            "api_response_format": "{services: [{name, status, latency_ms, last_check}], overall: 'healthy'|'degraded'|'down'}",
            "backend_app": "controlpanel",
            "backend_urls_file": "backend/controlpanel/urls.py",
            "backend_urls_status": "route_exists",
            "backend_views_file": "backend/controlpanel/api_views.py",
            "backend_view_function": "dashboard_system_health_view",
            "backend_views_status": "working",
            "backend_serializer": "Inline dict",
            "backend_serializer_status": "working",
            "backend_models": "HealthCheck records",
            "backend_models_status": "working",
            "db_has_data": "yes",
            "db_record_count": "Service checks",
            "pipeline_status": "partial",
            "data_source": "live_api",
            "verified_by": "aaron",
            "blocking_issue": "Some health checks returning mock data",
            "next_action": "Wire up actual service health checks for all components",
            "priority": "P1",
            "environment_zone": "internal_lab",
            "error_count": 2,
        },
        {
            "panel_id": "sessions-chart",
            "hover_name": "Sessions Chart",
            "description": "Time-series chart showing session activity over time",
            "frontend_component": "components/dashboard-overview.tsx",
            "frontend_hook": "useSessionsChart({ days: 7 })",
            "frontend_hook_status": "working",
            "api_client_file": "lib/api/nasa-lab.ts",
            "api_client_function": "fetchSessionsChart()",
            "api_client_status": "working",
            "api_endpoint": "/api/controlpanel/nasa/dashboard/sessions-chart/",
            "api_method": "GET",
            "api_auth_type": "admin_token",
            "api_request_status": "200",
            "api_response_format": "{data: [{date, count, completed, abandoned}], summary: {total, trend}}",
            "backend_app": "controlpanel",
            "backend_urls_file": "backend/controlpanel/urls.py",
            "backend_urls_status": "route_exists",
            "backend_views_file": "backend/controlpanel/api_views.py",
            "backend_view_function": "dashboard_sessions_chart_view",
            "backend_views_status": "working",
            "backend_serializer": "Inline dict",
            "backend_serializer_status": "working",
            "backend_models": "SimSession aggregates by day",
            "backend_models_status": "working",
            "db_has_data": "yes",
            "db_record_count": "7-30 days of data",
            "pipeline_status": "fully_connected",
            "data_source": "live_api",
            "verified_by": "aaron",
            "blocking_issue": "",
            "next_action": "Done",
            "priority": "P3",
            "environment_zone": "internal_lab",
            "error_count": 0,
        },
        {
            "panel_id": "kpi-summary",
            "hover_name": "KPI Summary",
            "description": "Key performance indicators summary panel",
            "frontend_component": "components/dashboard-overview.tsx",
            "frontend_hook": "useKPISummary()",
            "frontend_hook_status": "working",
            "api_client_file": "lib/api/nasa-lab.ts",
            "api_client_function": "fetchKPISummary()",
            "api_client_status": "working",
            "api_endpoint": "/api/controlpanel/nasa/dashboard/kpi-summary/",
            "api_method": "GET",
            "api_auth_type": "admin_token",
            "api_request_status": "200",
            "api_response_format": "{pass_rate, avg_score, completion_rate, avg_duration_min}",
            "backend_app": "controlpanel",
            "backend_urls_file": "backend/controlpanel/urls.py",
            "backend_urls_status": "route_exists",
            "backend_views_file": "backend/controlpanel/api_views.py",
            "backend_view_function": "dashboard_kpi_summary_view",
            "backend_views_status": "working",
            "backend_serializer": "Inline dict",
            "backend_serializer_status": "working",
            "backend_models": "CaseRun aggregates",
            "backend_models_status": "working",
            "db_has_data": "yes",
            "db_record_count": "Aggregated KPIs",
            "pipeline_status": "fully_connected",
            "data_source": "live_api",
            "verified_by": "atlas",
            "blocking_issue": "",
            "next_action": "Done",
            "priority": "P3",
            "environment_zone": "internal_lab",
            "error_count": 0,
        },
        {
            "panel_id": "ai-performance",
            "hover_name": "AI Performance",
            "description": "AI system performance metrics and latency stats",
            "frontend_component": "components/dashboard-overview.tsx",
            "frontend_hook": "useAIPerformance()",
            "frontend_hook_status": "working",
            "api_client_file": "lib/api/nasa-lab.ts",
            "api_client_function": "fetchAIPerformance()",
            "api_client_status": "working",
            "api_endpoint": "/api/controlpanel/nasa/dashboard/ai-performance/",
            "api_method": "GET",
            "api_auth_type": "admin_token",
            "api_request_status": "200",
            "api_response_format": "{avg_response_ms, p95_latency, tokens_per_session, cost_per_session}",
            "backend_app": "controlpanel",
            "backend_urls_file": "backend/controlpanel/urls.py",
            "backend_urls_status": "route_exists",
            "backend_views_file": "backend/controlpanel/api_views.py",
            "backend_view_function": "dashboard_ai_performance_view",
            "backend_views_status": "working",
            "backend_serializer": "Inline dict",
            "backend_serializer_status": "working",
            "backend_models": "AIMetrics, SessionMessage latency",
            "backend_models_status": "working",
            "db_has_data": "yes",
            "db_record_count": "Performance logs",
            "pipeline_status": "partial",
            "data_source": "live_api",
            "verified_by": "aaron",
            "blocking_issue": "Cost tracking not fully implemented",
            "next_action": "Add token counting and cost calculation to AI calls",
            "priority": "P2",
            "environment_zone": "internal_lab",
            "error_count": 1,
        },
        {
            "panel_id": "case-completion",
            "hover_name": "Case Completion",
            "description": "Case completion rates and status breakdown",
            "frontend_component": "components/dashboard-overview.tsx",
            "frontend_hook": "useCaseCompletion()",
            "frontend_hook_status": "working",
            "api_client_file": "lib/api/nasa-lab.ts",
            "api_client_function": "fetchCaseCompletion()",
            "api_client_status": "working",
            "api_endpoint": "/api/controlpanel/nasa/dashboard/case-completion/",
            "api_method": "GET",
            "api_auth_type": "admin_token",
            "api_request_status": "200",
            "api_response_format": "{by_case: [{case_id, completions, pass_rate}], total_completions}",
            "backend_app": "controlpanel",
            "backend_urls_file": "backend/controlpanel/urls.py",
            "backend_urls_status": "route_exists",
            "backend_views_file": "backend/controlpanel/api_views.py",
            "backend_view_function": "dashboard_case_completion_view",
            "backend_views_status": "working",
            "backend_serializer": "Inline dict",
            "backend_serializer_status": "working",
            "backend_models": "CaseRun by case aggregates",
            "backend_models_status": "working",
            "db_has_data": "yes",
            "db_record_count": "Per-case stats",
            "pipeline_status": "fully_connected",
            "data_source": "live_api",
            "verified_by": "atlas",
            "blocking_issue": "",
            "next_action": "Done",
            "priority": "P3",
            "environment_zone": "internal_lab",
            "error_count": 0,
        },
    ]

    # Import AI Tester page
    result1 = import_page(
        "ai-tester",
        "AI Tester",
        "AI testing control panel with 20 monitoring panels for automated simulation testing",
        ai_tester_panels,
        dry_run=args.dry_run
    )

    # Import Dashboard Overview page
    result2 = import_page(
        "dashboard-overview",
        "Dashboard Overview",
        "Main dashboard with 8 overview panels for system monitoring and KPIs",
        dashboard_panels,
        dry_run=args.dry_run
    )

    print("\n" + "=" * 60)
    print("Import Complete")
    print("=" * 60)

    if args.dry_run:
        print("DRY RUN - No data was actually imported")
    else:
        print(f"AI Tester page: {result1.get('success', False)}")
        print(f"Dashboard Overview page: {result2.get('success', False)}")


if __name__ == "__main__":
    main()
