#!/bin/bash
# Install all trigger sources for the fleet audit pipeline on this node.
#
# Wires up:
#   1. xbar plugin (symlink so updates land without re-install)
#   2. git post-commit hook (runs the tick after every commit)
#   3. git post-merge hook (runs the tick after every pull/merge)
#
# Idempotent. Safe to re-run. Removes nothing without --uninstall.
#
# Usage:
#   bash scripts/install-fleet-audit-triggers.sh
#   bash scripts/install-fleet-audit-triggers.sh --uninstall

set -e

UNINSTALL=0
[ "$1" = "--uninstall" ] && UNINSTALL=1

REPO=""
for d in "$HOME/dev/er-simulator-superrepo" "$HOME/Documents/er-simulator-superrepo"; do
    [ -d "$d" ] && REPO="$d" && break
done
[ -z "$REPO" ] && { echo "ERR: superrepo not found"; exit 1; }

XBAR_DIR="$HOME/Library/Application Support/xbar/plugins"
XBAR_LINK="$XBAR_DIR/fleet-audit-watchdog.30s.sh"
XBAR_SRC="$REPO/scripts/xbar-fleet-audit-watchdog.30s.sh"

GIT_DIR="$REPO/.git"
HOOK_POST_COMMIT="$GIT_DIR/hooks/post-commit"
HOOK_POST_MERGE="$GIT_DIR/hooks/post-merge"

if [ "$UNINSTALL" = "1" ]; then
    echo "[uninstall] xbar link"
    [ -L "$XBAR_LINK" ] && rm -f "$XBAR_LINK"
    echo "[uninstall] git hook fleet-audit blocks"
    for h in "$HOOK_POST_COMMIT" "$HOOK_POST_MERGE"; do
        if [ -f "$h" ]; then
            # Strip our block. Marker comments delimit it.
            sed -i.bak '/# >>> fleet-audit-tick >>>/,/# <<< fleet-audit-tick <<</d' "$h"
            rm -f "${h}.bak"
        fi
    done
    echo "[uninstall] done"
    exit 0
fi

# 1. xbar plugin (symlink)
mkdir -p "$XBAR_DIR"
chmod +x "$XBAR_SRC"
ln -sf "$XBAR_SRC" "$XBAR_LINK"
echo "[install] xbar: $XBAR_LINK -> $XBAR_SRC"

# 2 + 3. git hooks
install_hook() {
    local hook="$1"
    local label="$2"
    if [ ! -f "$hook" ]; then
        cat > "$hook" <<'HEAD'
#!/bin/bash
# auto-generated by scripts/install-fleet-audit-triggers.sh
HEAD
        chmod +x "$hook"
    fi
    if grep -q "fleet-audit-tick" "$hook" 2>/dev/null; then
        echo "[install] $label: already wired (no change)"
        return
    fi
    cat >> "$hook" <<HOOK
# >>> fleet-audit-tick >>>
# Trigger fleet audit detectors after $label. Background, non-blocking.
(
    cd "\$(git rev-parse --show-toplevel)" 2>/dev/null || exit 0
    PY="multi-fleet/venv.nosync/bin/python3"
    [ -x "\$PY" ] || PY="\$(command -v python3)"
    [ -x "\$PY" ] || exit 0
    "\$PY" scripts/fleet-audit-tick.py --source git-$label --no-consult --no-chief \\
        > /tmp/fleet-audit-git-$label.log 2>&1 &
    disown
) || true
# <<< fleet-audit-tick <<<
HOOK
    echo "[install] $label: hook block appended to $hook"
}

install_hook "$HOOK_POST_COMMIT" "post-commit"
install_hook "$HOOK_POST_MERGE" "post-merge"

echo
echo "[install] done. Triggers:"
echo "  - xbar plugin (30s OS scheduler)"
echo "  - git post-commit (every commit)"
echo "  - git post-merge (every pull/merge)"
echo
echo "Manual tick: $REPO/multi-fleet/venv.nosync/bin/python3 $REPO/scripts/fleet-audit-tick.py"
