#!/usr/bin/env bash
#
# wire-submodules.sh — wire the ContextDNA IDE mothership submodules
#
# Usage: wire-submodules.sh <target-dir>
#
# Adds the four mothership submodules (3-surgeons, multi-fleet, context-dna,
# ide-shell) into <target-dir> via `git submodule add`. Unreachable remotes are
# logged to submodule-todo.md and skipped — they do not fail the run.
#
# Pinning: if a file named <repo>.pinned sits alongside this script with the
# format "path SHA" per line, each matching submodule is checked out to that
# SHA. Otherwise the upstream HEAD is used.
#
# ZSF (Zero Silent Failures): every branch increments a counter. The final
# summary on stderr surfaces WIRED / SKIPPED_UNREACHABLE / PINNED / ERRORS.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET="${1:-}"

if [[ -z "$TARGET" ]]; then
    echo "ERROR: target directory required" >&2
    echo "usage: $0 <target-dir>" >&2
    exit 2
fi

if [[ ! -d "$TARGET" ]]; then
    echo "ERROR: target dir does not exist: $TARGET" >&2
    exit 2
fi

# Verify target is a git repo
if ! git -C "$TARGET" status >/dev/null 2>&1; then
    echo "ERROR: target dir is not a git repo: $TARGET" >&2
    exit 2
fi

TODO_FILE="$TARGET/submodule-todo.md"
PINNED_FILE_3S="$SCRIPT_DIR/3-surgeons.pinned"
PINNED_FILE_MF="$SCRIPT_DIR/multi-fleet.pinned"
PINNED_FILE_CDNA="$SCRIPT_DIR/context-dna.pinned"
PINNED_FILE_IDE="$SCRIPT_DIR/ide-shell.pinned"

# Counters (ZSF)
WIRED=0
SKIPPED_UNREACHABLE=0
PINNED=0
ERRORS=0

# Submodule definitions: name|path|url|pinned-file
SUBMODULES=(
    "3-surgeons|engines/3-surgeons|https://github.com/supportersimulator/3-surgeons.git|$PINNED_FILE_3S"
    "multi-fleet|engines/multi-fleet|https://github.com/supportersimulator/multi-fleet.git|$PINNED_FILE_MF"
    "context-dna|engines/context-dna|https://github.com/supportersimulator/context-dna.git|$PINNED_FILE_CDNA"
    "ide-shell|apps/ide-shell|https://github.com/supportersimulator/v0-Context-DNA-1.git|$PINNED_FILE_IDE"
)

note_todo() {
    local msg="$1"
    {
        if [[ ! -s "$TODO_FILE" ]]; then
            echo "# Submodule TODOs"
            echo ""
            echo "Generated by wire-submodules.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
            echo ""
        fi
        echo "- $msg"
    } >> "$TODO_FILE"
}

reachable() {
    local url="$1"
    # 5s timeout — works on both gtimeout (coreutils) and timeout (linux)
    local tcmd=""
    if command -v timeout >/dev/null 2>&1; then
        tcmd="timeout 5"
    elif command -v gtimeout >/dev/null 2>&1; then
        tcmd="gtimeout 5"
    fi
    if [[ -n "$tcmd" ]]; then
        $tcmd git ls-remote "$url" HEAD >/dev/null 2>&1
    else
        # No timeout available — accept slower fallback but cap via GIT_HTTP_LOW_SPEED
        GIT_HTTP_LOW_SPEED_LIMIT=1 GIT_HTTP_LOW_SPEED_TIME=5 \
            git ls-remote "$url" HEAD >/dev/null 2>&1
    fi
}

lookup_pinned_sha() {
    local pinned_file="$1"
    local path="$2"
    [[ -f "$pinned_file" ]] || return 1
    awk -v p="$path" '$1 == p { print $2; exit }' "$pinned_file"
}

wire_one() {
    local name="$1" path="$2" url="$3" pinned_file="$4"

    echo ">> $name ($path)" >&2

    if ! reachable "$url"; then
        echo "   unreachable: $url — skipping" >&2
        note_todo "**$name** — remote unreachable: \`$url\` (verify public URL or swap to private mirror)"
        SKIPPED_UNREACHABLE=$((SKIPPED_UNREACHABLE + 1))
        return 0
    fi

    if git -C "$TARGET" submodule add "$url" "$path" 2>&1 | sed 's/^/   /' >&2; then
        WIRED=$((WIRED + 1))
    else
        echo "   ERROR: submodule add failed for $name" >&2
        ERRORS=$((ERRORS + 1))
        return 0
    fi

    local pinned_sha
    pinned_sha=$(lookup_pinned_sha "$pinned_file" "$path" 2>/dev/null || true)
    if [[ -n "${pinned_sha:-}" ]]; then
        echo "   pinning to $pinned_sha" >&2
        if git -C "$TARGET/$path" fetch --depth 1 origin "$pinned_sha" 2>/dev/null \
           && git -C "$TARGET/$path" checkout --detach "$pinned_sha" 2>&1 | sed 's/^/   /' >&2; then
            # Stage the gitlink update so the operator's commit captures the pin
            git -C "$TARGET" add "$path" 2>/dev/null || true
            PINNED=$((PINNED + 1))
        else
            echo "   WARN: could not pin $name to $pinned_sha — leaving at HEAD" >&2
            note_todo "**$name** — failed to pin to \`$pinned_sha\`, currently at upstream HEAD"
            ERRORS=$((ERRORS + 1))
        fi
    else
        echo "   no pin file entry — staying at HEAD" >&2
    fi
}

for entry in "${SUBMODULES[@]}"; do
    IFS='|' read -r name path url pinned_file <<< "$entry"
    wire_one "$name" "$path" "$url" "$pinned_file"
done

cat >&2 <<SUMMARY

============================================================
wire-submodules.sh summary
============================================================
  WIRED                = $WIRED
  SKIPPED_UNREACHABLE  = $SKIPPED_UNREACHABLE
  PINNED               = $PINNED
  ERRORS               = $ERRORS

Target: $TARGET
TODO log: $TODO_FILE (only written if entries exist)

Changes are staged but NOT committed. Review with:
  git -C "$TARGET" status
  git -C "$TARGET" diff --cached

Then commit when satisfied.
============================================================
SUMMARY

if [[ "$ERRORS" -gt 0 ]]; then
    exit 1
fi
exit 0
